matrix:
      - PKG: [resummino]
        VERSION: [3.1.1]
        CATEGORY: ['sci-physics']
      - PKG: [handyg]
        VERSION: [0.1.5]
        CATEGORY: ['sci-libs']
      - PKG: [oneloop]
        VERSION: [2020.07.31]
        CATEGORY: ['sci-physics']
      - PKG: [qcdloop]
        VERSION: [2.0.9, 2.0.5]
        CATEGORY: ['sci-physics']
      - PKG: [mcfm]
        VERSION: ['10.2.1']
        CATEGORY: ['sci-physics']
      - PKG: [yoda]
        VERSION: [1.9.5]
        CATEGORY: ['sci-physics']
      - PKG: [hepmc]
        VERSION: [3.2.5, 2.06.11]
        CATEGORY: ['sci-physics']
      - PKG: [pythia]
        VERSION: [8.3.07, 8.2.45]
        CATEGORY: ['sci-physics']
      - PKG: [rivet]
        VERSION: [3.1.6, 3.1.5]
        CATEGORY: ['sci-physics']
      - PKG: [fastjet]
        VERSION: [3.4.0, 3.0.6]
        CATEGORY: ['sci-physics']
      - PKG: [fastjet-contrib]
        VERSION: ['1.049']
        CATEGORY: ['sci-physics']
      - PKG: [qgraf]
        VERSION: [3.6.3, 3.5.2, 3.4.2]
        CATEGORY: ['sci-physics']
      - PKG: [topdrawer]
        VERSION: ['9999']
        CATEGORY: ['sci-physics']
      - PKG: [looptools]
        VERSION: ['2.16', '2.15']
        CATEGORY: ['sci-physics']
      - PKG: [lhapdf]
        VERSION: [6.5.3, 6.3.0, 6.2.3-r1]
        CATEGORY: ['sci-physics']
      - PKG: [madgraph]
        VERSION: ['3.3.1']
        CATEGORY: ['sci-physics']
