.images: &images
  IMAGE:
    [
      apnpucky/gentoo-hep-forge:latest,
      apnpucky/gentoo-hep-forge-unstable:latest,
    ]

.matrix: &matrix
  parallel:
    matrix:
      - CATEGORY: ["sci-physics"]
        PKG: [hepmc]
        VERSION: [9999, "3.2.7", 3.2.6, 3.2.5, 2.06.11]
        ARCH: [amd64, arm64, arm, riscv]
        <<: *images

include: '/.gitlab-ci-child.yml'

check:
  extends: .check
  <<: *matrix

warn:
  extends: .warn
  <<: *matrix

build:
  extends: .build
  <<: *matrix

test:
  extends: .test
  <<: *matrix

qa:
  extends: .qa
  <<: *matrix